### PR TITLE
merge

### PR DESCRIPTION
**Pull request by thomhastings**
2 solutions is better than 1

### CODE REVIEW

**Comment by thomhastings** [comment]
Hi brianckeegan/CodeFor,

I&#39;d like to add you to my professional network on LinkedIn.

- Thom

Accept: https://www.linkedin.com/blink?simpleRedirect=0OejcVdPsMdjcMc3cTcPwUd3ARfkh9rCZFt65QqnpKqioUgQcQgllUt3RVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9DwRbj5IqSJNujhFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=u3kJcmNHqT5Vd6AJonhxqD4QfmhFpipmujANukxRrAxOsAlak4sVom5NhmxImkJ4ljdncRZSc2RxiC5hlkB9pn5ggRtRu7BFk3dHuCFPk5xQjTBPgQQNqn1WeklRdDtqhkdodl1Np7EUkCFHhyRAlnt2knpNq5BWel4Qt4J9cRljomlVkk9PhnsUu6h1lStPiDl6jnxIcSgPt5tDtR9iiz9TkAYUdTkThDkQuAdorjAPl7p4emN1lQl2cA8VlQV8en1UnRAUuDpOlk51gl54nTlvpPkNtBhKhB51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DwRbj5IqSJNujhFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5961626682258395136_500&amp;markAsRead=This email was intended for brianckeegan/CodeFor brianckeegan/CodeForAmerica. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DwRbj5IqSJNujhFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thomhastings** [comment]
Hi brianckeegan/CodeFor,

I&#39;d like to add you to my professional network on LinkedIn.

- Thom

Accept: https://www.linkedin.com/blink?simpleRedirect=0Mc30MczkVcP4Ud3ASczoNdzARfkh9rCZFt65QqnpKqip8cCV8iBtzhjRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CkRbmdDcmRNujhFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=pjkJoSsNrn5Vd6AJt31StSFKfmhFpipzkl4SekwJd35WtnBobmh3rSFLlQ5jkDETjmZhokkUpAVOej9IrCBocjhmdSVApDFahkV3smVBl3xad75WjjtSnSpVknoTu4dCiAFNt6Rge7hmj5BWk5oUpS9zi5xKoRl2im4JmkRVgCsJejdJcD1JdmVyu7BxcT53hk5jiiRNrCdCrAROgSYRs6EQlkx5r4pqd5cMm4gOtRxal4sUblcShSdBr4VBdQZzczhTik9bc7pOlk51gl4Uj4tdmC9xpmZLhl51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CkRbmdDcmRNujhFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5961626969803096064_500&amp;markAsRead=This email was intended for brianckeegan/CodeFor brianckeegan/CodeForAmerica. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CkRbmdDcmRNujhFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by attackvector** [comment]
Why hello, CfA. Remember CodeCorps?

**Comment by thomhastings** [comment]
Thom Hastings would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0OejcVdPsMdjcMc3cTcPwUd3ARfkh9rCZFt65QqnpKqioUgQcQgllUt3RVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CUSbn9WpCQOdjlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=

View Thom Hastings&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CUSbn9WpCQOdjlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mcPdShBp38MpmcVdz5xczByd30SdjwMcj4Mc30Mc30MpCcOejBCoPsMcjBCe3lxpzwUojcPc3gUp3sTem5ze3gQdS5Ac6gPpC4Mc6cUczsOcj0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z8VcPATdP0RcP0McPsPe3wQejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CUSbn9WpCQOdjlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1KdyROuCpJczkRqiRxt65GsjgZp6BB9CppdRhjpllykjBQh2RGjOR1cQtBumRomB15pP56bmZeoRhSmBxIlSRIulBkh6NhpldPjQxIuCAOmmFFumhotTtdtTEJlQx7jnFRmCRzt4Niq31Cp4phsShFsCRNqz5jgnF2p7h6gRB9hyRgpl9xkS5dcRF4onF8gTwUcktWmBtHl6Vel5x9cTxNi58Nt4hWl4Zhe6JgoAhGskJ6llxagT5BlD54lARBsjxVoTkVdAtMhTdlgk51glpfjncMoS9BqSV6kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CUSbn9WpCQOdjlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5961626682258395136_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CUSbn9WpCQOdjlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thomhastings** [comment]
Thom Hastings would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Mc30MczkVcP4Ud3ASczoNdzARfkh9rCZFt65QqnpKqip8cCV8iBtzhjRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CYObj1Nq6QOdjlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=

View Thom Hastings&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CYObj1Nq6QOdjlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mcPdShBp38MpmcVdz5xczBzczkVdm8Mcj4Mc30Mc30MpCcOej9zpjASdzlzpjhCpzAVoj0Soj9Acmhxp69AejgPp35AejkVpCcQcCcUczsOcj0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0Mc30OdjAPcjwQejoOdz4SejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CYObj1Nq6QOdjlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1LcyQMsmxJczkRqiRQc7pTqCUZp6BB9CtSmCZVj6pjuB0Ml4Fzp59pq3gJsnF9iCd5sQkOcn1fr6JVpiQNpklCt6dEmmh8d3BhpAxlpSoVgTlHm4YMiCZBilhEgANlrlFzt69WcSF9jT9Md6ZKi5denPhIcRdqom9kpTh6lmcSjCV3l78RiSxpenBDh5xRsQxGqDxGbmV3oTtgq6R5j5FStkder7FBgD5UqBlfhkN7gjdahCdoqkRQk2QStk9dmmpbhmRHdQpMhTdlgk51pQ5RkSN1dD11ul55kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CYObj1Nq6QOdjlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5961626969803096064_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CYObj1Nq6QOdjlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by attackvector** [comment]
this is awesome I totally hope I can call this a finding

**Comment by thomhastings** [comment]
Thom HastingsさんからLinkedInのつながりリクエストが届いています。 忘れないうちに対応しましょう。

承認する: https://www.linkedin.com/blink?simpleRedirect=0OejcVdPsMdjcMc3cTcPwUd3ARfkh9rCZFt65QqnpKqioUgQcQgllUt3RVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9DsObjsQsmNNp3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=

Thom Hastingsさんのプロフィールを表示する: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9DsObjsQsmNNp3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=

このメールは、未対応のつながりリクエストをお知らせするものです。配信を停止する: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mcPdShBp38MpmcVdz5xczByd30SdjwMcj4Mc30Mc30MpCcOejBCoPsMcjBCe3lxpzwUojcPc3gUp3sTem5ze3gQdS5Ac6gPpC4Mc6cUczsOcj0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z8VcPATdP0RcP0McPsPe3wQejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9DsObjsQsmNNp3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=

本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。メール購読を停止するには次のリンクをクリックしてください: https://www.linkedin.com/blink?simpleRedirect=1TcyQTd75IsmgRqiRxt65GsjgZp6BB9DBiijlptz58elFOdThNu5h5d7oNmmZzsQ9JsS58qRpyrl51pQtigz5QckMQt6h8hCNxbmoTpABNtTcQjyR5tBhNdChHpBoRklZHhAx1tCF4h7wMoSNypmESoPxehS8QqC9Ee7l1dyQNdCIMtRlInSdBsDFgcl4TlzxntjoNcToQljlBl3BcsSdAm45Jql1PpPtar656cCd2ilFju5YRrjpemANihlcQhQhkunFGbk4Qr7dlgk51gmVhrAtCjkhBdlh7kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DsObjsQsmNNp3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5961626682258395136_500&amp;markAsRead= 個人情報保護に向けたLinkedInの取り組みについてはこちらをご覧ください: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DsObjsQsmNNp3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626682258395136_500&markAsRead=
&copy;2014, LinkedIn Corporation.2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thomhastings** [comment]
Thom HastingsさんからLinkedInのつながりリクエストが届いています。 忘れないうちに対応しましょう。

承認する: https://www.linkedin.com/blink?simpleRedirect=0Mc30MczkVcP4Ud3ASczoNdzARfkh9rCZFt65QqnpKqip8cCV8iBtzhjRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9DwPbmlDsCNNp3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=

Thom Hastingsさんのプロフィールを表示する: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9DwPbmlDsCNNp3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=

このメールは、未対応のつながりリクエストをお知らせするものです。配信を停止する: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mcPdShBp38MpmcVdz5xczBzczkVdm8Mcj4Mc30Mc30MpCcOej9zpjASdzlzpjhCpzAVoj0Soj9Acmhxp69AejgPp35AejkVpCcQcCcUczsOcj0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0Mc30OdjAPcjwQejoOdz4SejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9DwPbmlDsCNNp3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=

本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。メール購読を停止するには次のリンクをクリックしてください: https://www.linkedin.com/blink?simpleRedirect=1UcORBpT9IsmgRqiRQc7pTqCUZp6BB9z1RmCt7ikZElnxLe49Esn5Fp6ZUgnhnrjd1d6Rak4N4u7tDrTlip35hm3dljA9piCBpslBqe4tSlk5QqSgVkCpNuAkNkBtVpPhahQtlp5ZRnRgUe7dilCBnon5ikjxPtzhNdB1vjzxMckZPt4dCq7BhpBpfcz4MdSpAu51Vij5mqQpGokRBrnpRmCVViC9Hol5dsB5ebntAkQ4PsRt3rP1FkCNxl7xFi39RgkR5oQ8Qr7dlgk51tQ9ngS5Dpn5bmmZ5kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DwPbmlDsCNNp3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5961626969803096064_500&amp;markAsRead= 個人情報保護に向けたLinkedInの取り組みについてはこちらをご覧ください: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DwPbmlDsCNNp3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5961626969803096064_500&markAsRead=
&copy;2014, LinkedIn Corporation.2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by attackvector** [comment]
GitHub I love you.

**Comment by attackvector** [comment]
@thomhastings I love you too, dude.

**Comment by thomhastings** [comment]
Hi brianckeegan/CodeFor,

I&#39;d like to add you to my professional network on LinkedIn.

- Thom

Accept: https://www.linkedin.com/blink?simpleRedirect=0Mc30MczkVcP4Ud3ASczoNdzARfkh9rCZFt65QqnpKqip8cCV8iBtzhjRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9zkQbmxOoTkMu3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321904408489984_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=djgJq79ztj1UdmAJt31StSFKfmhFpipkgnBnlQZ1oSUShnlRgTB2in9juAsUcA9qjThTu4litORkhAMRh3xScRBSm556cndhqQhhsD1bq5xRiTtpjkJNqSdDgDxopQIVpSN8j6NbuCpkum5Nh51iiQ5Hl3xCjCFOekJbc4cSlAh8i6Zkl5xPjP0TgkN4q3t3hiR7dQ8QgnAOiBhWk6tFcPdzkT4QjShJiSxQj515dkVQtApClj1Tt49pjlhxdCRSmjpInQVcmn9Qlk51gl5au71itzBRoOQVhl51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9zkQbmxOoTkMu3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5970321904408489984_500&amp;markAsRead=This email was intended for brianckeegan/CodeFor brianckeegan/CodeForAmerica. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zkQbmxOoTkMu3lFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321904408489984_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thomhastings** [comment]
Hi brianckeegan/CodeFor,

I&#39;d like to add you to my professional network on LinkedIn.

- Thom

Accept: https://www.linkedin.com/blink?simpleRedirect=0OejcVdPsMdjcMc3cTcPwUd3ARfkh9rCZFt65QqnpKqioUgQcQgllUt3RVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9D8NbnBKoTkMu3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321903661907969_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=sz4JumVztj1UdmAJonhxqD4QfmhFpipblORCkQ99h49VsR9RijtabntJlD5xgkdMtjhduAQUhAxDdABpqTBJqBB2dl9jtPcSq7dApDEOc3kJlkdMul9jcABWmB91lmcOpB9IimVOqQpNumNEsnxdd74Jr6Z9ekZ5sm5inT9jm6loiAcRi5FWjkREr55lrCV7oTpMtA5vq4plen9QhmQTtQlNkmZCsSwMiAFEt3h2dD0Ve4llmBtAczhnhPlBcAdGlANAj5Zdmn9Qlk51gntKt69oqkMNoAVBi551fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9D8NbnBKoTkMu3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5970321903661907969_500&amp;markAsRead=This email was intended for brianckeegan/CodeFor brianckeegan/CodeForAmerica. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9D8NbnBKoTkMu3lFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321903661907969_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thomhastings** [comment]
Thom Hastings would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0OejcVdPsMdjcMc3cTcPwUd3ARfkh9rCZFt65QqnpKqioUgQcQgllUt3RVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9z4NbmENqP8OuzlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321903661907969_500&markAsRead=

View Thom Hastings&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9z4NbmENqP8OuzlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321903661907969_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mcPdShBp38MpmcVdz5xczByd30SdjwMcj4Mc30Mc30MpCcOejBCoPsMcjBCe3lxpzwUojcPc3gUp3sTem5ze3gQdS5Ac6gPpC4Mc6cUczsOcj0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z8VcPATdP0RcP0McPsPe3wQejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9z4NbmENqP8OuzlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321903661907969_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=0NciRGcmIOcDERqiRxt65GsjgZp6BB9Bdjm5cUml5csmNGnRtge6xyiPAPt5dKd55CiRtBtThoc6t8i3pju5Zeln8OjDoOrCxMbkl1qShdp6ROcmZNrCoRmDtlcRpduCl4pRd8cQIUqkEPkSx8r6hGjzgQmkBVoCNMiS5ApjtigAEToAhChD5dhjBFlldQk79Ahn5osP5WqRtWtjkVlz1TcktBhl0SjDFAh3sNi5Fdljt4u3hkrAFbulZSdkFmrldHrOQTu5xQunhlgk51gl1RklgMuCUNoj56kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9z4NbmENqP8OuzlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5970321903661907969_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9z4NbmENqP8OuzlFbm5QomFNd3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321903661907969_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thomhastings** [comment]
Thom Hastings would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Mc30MczkVcP4Ud3ASczoNdzARfkh9rCZFt65QqnpKqip8cCV8iBtzhjRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9DoSbjBUtngOuzlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321904408489984_500&markAsRead=

View Thom Hastings&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9DoSbjBUtngOuzlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321904408489984_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mcPdShBp38MpmcVdz5xczBzczkVdm8Mcj4Mc30Mc30MpCcOej9zpjASdzlzpjhCpzAVoj0Soj9Acmhxp69AejgPp35AejkVpCcQcCcUczsOcj0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0Mc30OdjAPcjwQejoOdz4SejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9DoSbjBUtngOuzlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321904408489984_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1SdyQVu7lQcDERqiRQc7pTqCUZp6BB9AVdkPl4hjh7gSJvmzdNdz1acRlykAlBhAlHuDBBe6V6pzdFimZRpkRMuBhnsSpLln5Fd2RNrSt1k44Os4R8l3xWsPdlrA4Nc554gm5CgQ5Jbj5DjDphsndfckpDu4FnhQ5Frz4OoB1OlCJEhj5mqz1LiBhVmllUdk58k6BBpmlKk7hUdQxxgANvu4JHbnF8pkJBklxGkDFPnRx4uA9vbmVzr352qRlRej12rltHs4RVunhlgk51kmxQjAdaumRghnF8kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DoSbjBUtngOuzlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5970321904408489984_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DoSbjBUtngOuzlFbngMtDtGrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970321904408489984_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Pull request closed without merging**
